[package]
name = "hapke-demo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = "0.37.0"
tiff = "0.10.0"
egui = "0.31.1"
egui_sdl2_gl = "0.31.0"
glm = "0.2.3"
glow = "0.16.0"
wide = "0.7.32"
